solve1:
	nasm -f elf32 funcs.asm && nasm -f elf32 rps1.asm && nasm -f elf32 main.asm && ld -m elf_i386 -o solve1 main.o funcs.o rps1.o

solve2:
	nasm -f elf32 funcs.asm && nasm -f elf32 rps2.asm && nasm -f elf32 main.asm && ld -m elf_i386 -o solve2 main.o funcs.o rps2.o
